"""AI-powered office configuration generator.

Uses `docker exec ... claude` to leverage the already-authenticated Claude CLI
inside the office's Docker container.

Generation is split into 4 phases, each a separate Claude CLI call:
1. Office instructions (CLAUDE.md)
2. Agent roster (names, roles, tools — no full prompts)
3. Individual agent details (system_prompt + claude_md_content, one per agent)
4. Skills + playbooks

This avoids timeouts for large offices (20-30 agents) and provides real-time
progress updates per agent.
"""

from __future__ import annotations

import asyncio
import json
import logging
import subprocess
import uuid
from typing import Any

logger = logging.getLogger(__name__)

# Per-chunk timeout (each chunk is small — one agent, one skill set, etc.)
_CHUNK_TIMEOUT = 120

# Max retries per chunk
_MAX_RETRIES = 2

# ---------------------------------------------------------------------------
# System prompts for each phase
# ---------------------------------------------------------------------------

ANALYZE_SYSTEM_PROMPT = """\
You are an expert at analyzing office descriptions and extracting structured requirements.

Given a free-text description of an AI office, extract and expand the information into four fields.

CRITICAL: Every value MUST be a plain text string. NOT an array, NOT an object. Use newlines and bullet characters within the string for structure.

Output a JSON object exactly like this example:

{
  "responsibility_areas": "- Lead generation and qualification\\n- Sales pipeline management\\n- CRM data enrichment\\n- Outreach sequence creation",
  "desired_agents": "- Sales Researcher: Researches prospects and companies before outreach\\n- Outreach Specialist: Creates personalized email sequences\\n- Pipeline Analyst: Tracks conversion rates and pipeline health",
  "workflows": "1. Research target companies and contacts\\n2. Enrich prospect data from multiple sources\\n3. Create personalized outreach sequences\\n4. Track responses and engagement\\n5. Qualify leads and update pipeline",
  "additional_context": "We use Salesforce as our CRM. Target market is mid-market SaaS companies in North America. Team of 5 SDRs."
}

All four values are STRINGS containing formatted text. Be thorough — expand brief mentions into detailed descriptions.

Output ONLY the JSON object. No markdown, no code blocks, no extra text."""


INSTRUCTIONS_PROMPT = """\
You are an expert AI office configuration designer for the Cubicle platform.

Generate comprehensive office-level instructions (CLAUDE.md content) for an AI office.
These instructions are shared by ALL agents in the office and define:
- Office focus areas and priorities
- Team conventions and quality standards
- Communication style and output expectations
- Domain-specific terminology and rules
- File organization and naming conventions

Output a JSON object with a single field:
{
  "instructions": "# Office Instructions\\n\\n## Focus Areas\\n...\\n\\n## Conventions\\n..."
}

The instructions should be 300-800 words of practical markdown content.

Output ONLY the JSON. No markdown code blocks, no extra text."""


ROSTER_PROMPT = """\
You are an expert AI office configuration designer for the Cubicle platform.

The Cubicle platform has:
- **System Agents** (always present, NOT generated by you): Analyst, Automation Script Developer, Auditor, Manager Assistant
- **Custom Agents**: User-defined specialists that execute tasks

Generate a list of custom agents for this office. For each agent provide ONLY:
- name: lowercase-with-hyphens slug
- display_name: Human-readable name
- avatar_emoji: A relevant emoji (not robot)
- role_description: One-line description of the role
- model: "claude-sonnet-4-6" for most agents
- allowed_tools: List from [Read, Write, Bash, Glob, Grep, WebSearch, WebFetch]
  - Research agents: Read, Glob, Grep, WebSearch, WebFetch, Write
  - Development agents: Read, Write, Bash, Glob, Grep
  - Review agents: Read, Glob, Grep, Bash
- skill_names: List of skill slugs this agent needs (can be empty)

Do NOT include system_prompt or claude_md_content — those will be generated separately.

Output a JSON object:
{
  "agents": [
    {
      "name": "slug-name",
      "display_name": "Human Name",
      "avatar_emoji": "emoji",
      "role_description": "One-line role",
      "model": "claude-sonnet-4-6",
      "allowed_tools": ["Read", "Write", "Bash", "Glob", "Grep"],
      "skill_names": ["skill-slug"]
    }
  ]
}

Generate between 2 and 15 agents with specific, non-overlapping roles.

Output ONLY the JSON. No markdown code blocks, no extra text."""


AGENT_DETAIL_PROMPT = """\
You are an expert AI agent configuration designer for the Cubicle platform.

IMPORTANT: "system_prompt" and "claude_md_content" serve DIFFERENT purposes:
- "system_prompt" = AI role definition, personality, behavioral rules (WHO the agent IS)
- "claude_md_content" = practical workspace instructions, conventions, file paths, tools usage patterns, output format rules (HOW the agent WORKS)

Generate the full configuration for ONE specific agent. Output a JSON object:
{
  "system_prompt": "AI role definition: who this agent is, core responsibilities, decision-making principles, communication style (200-400 words)",
  "claude_md_content": "Practical workspace instructions: conventions, output formats, file naming, quality checklists, tool usage patterns, step-by-step processes (200-500 words markdown)"
}

Output ONLY the JSON. No markdown code blocks, no extra text."""


SKILLS_PROMPT = """\
You are an expert AI office configuration designer for the Cubicle platform.

Generate skills (capability playbooks) for this office. Each skill is a SKILL.md file
with YAML frontmatter that guides agents in specific tasks.

Output a JSON object:
{
  "skills": [
    {
      "name": "skill-slug-name",
      "display_name": "Skill Name",
      "description": "What this skill does",
      "playbook_content": "---\\nname: skill-slug-name\\ndescription: What this skill does\\n---\\n\\n# Skill Name Playbook\\n\\n## Process\\n1. Step one\\n2. Step two\\n\\n## Output Standards\\n- Standard one\\n- Standard two",
      "parameter_schema": []
    }
  ]
}

Generate skills that match the skill_names referenced by the agents. Include 0-8 skills.

Output ONLY the JSON. No markdown code blocks, no extra text."""


# ---------------------------------------------------------------------------
# Core CLI runner (unchanged)
# ---------------------------------------------------------------------------

async def _run_claude_cli(
    container_name: str,
    system_prompt: str,
    user_prompt: str,
    timeout: int = _CHUNK_TIMEOUT,
) -> str:
    """Run a Claude CLI query inside the Docker container."""
    sys_file = f"/tmp/cubicle_sys_{uuid.uuid4().hex[:8]}.txt"
    user_file = f"/tmp/cubicle_user_{uuid.uuid4().hex[:8]}.txt"

    try:
        await asyncio.to_thread(
            subprocess.run,
            ["docker", "exec", "-i", container_name, "tee", sys_file],
            input=system_prompt, capture_output=True, text=True, timeout=10,
        )
        await asyncio.to_thread(
            subprocess.run,
            ["docker", "exec", "-i", container_name, "tee", user_file],
            input=user_prompt, capture_output=True, text=True, timeout=10,
        )

        result = await asyncio.to_thread(
            subprocess.run,
            [
                "docker", "exec", container_name,
                "bash", "-c",
                f'cat "{user_file}" | claude --print'
                f" --output-format text"
                f" --max-turns 1"
                f" --model claude-sonnet-4-6"
                f" --permission-mode bypassPermissions"
                f' --system-prompt-file "{sys_file}"',
            ],
            capture_output=True, text=True, timeout=timeout,
        )

        if result.returncode != 0:
            stderr = result.stderr.strip()[:500]
            stdout = result.stdout.strip()[:500]
            raise RuntimeError(
                f"Claude CLI failed (rc={result.returncode}): {stderr or stdout}"
            )

        return result.stdout.strip()

    finally:
        asyncio.create_task(asyncio.to_thread(
            subprocess.run,
            ["docker", "exec", container_name, "rm", "-f", sys_file, user_file],
            capture_output=True, timeout=5,
        ))


async def _run_chunk(
    container_name: str,
    system_prompt: str,
    user_prompt: str,
    timeout: int = _CHUNK_TIMEOUT,
) -> dict[str, Any]:
    """Run a single chunk with retry. Returns parsed JSON."""
    last_error = None
    for attempt in range(_MAX_RETRIES + 1):
        try:
            raw = await _run_claude_cli(
                container_name, system_prompt, user_prompt, timeout=timeout,
            )
            return _parse_json_response(raw)
        except Exception as exc:
            last_error = exc
            if attempt < _MAX_RETRIES:
                logger.warning(
                    "Chunk failed (attempt %d/%d): %s — retrying...",
                    attempt + 1, _MAX_RETRIES + 1, exc,
                )
                await asyncio.sleep(2)
    raise last_error  # type: ignore[misc]


# ---------------------------------------------------------------------------
# Chunked generation
# ---------------------------------------------------------------------------

async def generate_office_config(
    router: object,
    request_id: str,
    office_name: str,
    office_description: str,
    requirements: dict[str, Any],
    container_name: str,
) -> None:
    """Generate office configuration in chunks with real-time progress."""
    try:
        base_context = _build_user_prompt(office_name, office_description, requirements)

        # ── Phase 1: Office Instructions ────────────────────────────────
        await _publish_progress(
            router, request_id,
            message="Generating office instructions...",
            step_number=1, total_steps=4,  # initial estimate
        )

        instructions_result = await _run_chunk(
            container_name, INSTRUCTIONS_PROMPT,
            f"Generate office instructions for:\n\n{base_context}",
        )
        instructions = instructions_result.get("instructions", "")
        logger.info("Phase 1 complete: instructions (%d chars)", len(instructions))

        # ── Phase 2: Agent Roster ───────────────────────────────────────
        await _publish_progress(
            router, request_id,
            message="Designing agent roster...",
            step_number=2, total_steps=4,
        )

        roster_result = await _run_chunk(
            container_name, ROSTER_PROMPT,
            f"{base_context}\n\n## Office Instructions\n{instructions}",
        )
        agents = roster_result.get("agents", [])
        agent_count = len(agents)

        # Now we know the real total: 2 (instructions + roster) + agents + 1 (skills)
        total_steps = 2 + agent_count + 1

        logger.info(
            "Phase 2 complete: %d agents in roster, total_steps=%d",
            agent_count, total_steps,
        )

        # Update progress with real total
        await _publish_progress(
            router, request_id,
            message=f"Agent roster ready ({agent_count} agents)",
            step_number=2, total_steps=total_steps,
        )

        # Build team summary for agent detail context
        team_summary = "\n".join(
            f"- {a.get('display_name', a['name'])} ({a.get('role_description', '')})"
            for a in agents
        )

        # ── Phase 3: Individual Agent Details ───────────────────────────
        for i, agent in enumerate(agents):
            step = 3 + i
            agent_name = agent.get("display_name", agent["name"])

            await _publish_progress(
                router, request_id,
                message=f"Creating agent {i + 1}/{agent_count}: {agent_name}...",
                step_number=step, total_steps=total_steps,
            )

            agent_context = (
                f"Generate the full configuration for this agent:\n\n"
                f"Name: {agent.get('name', '')}\n"
                f"Display Name: {agent_name}\n"
                f"Role: {agent.get('role_description', '')}\n"
                f"Tools: {', '.join(agent.get('allowed_tools', []))}\n"
                f"Skills: {', '.join(agent.get('skill_names', []))}\n\n"
                f"## Office Context\n"
                f"Office: {office_name}\n"
                f"Instructions summary: {instructions[:500]}\n\n"
                f"## Team (other agents):\n{team_summary}\n\n"
                f"## Requirements\n{base_context}"
            )

            detail = await _run_chunk(
                container_name, AGENT_DETAIL_PROMPT, agent_context,
            )
            agent["system_prompt"] = detail.get("system_prompt", "")
            agent["claude_md_content"] = detail.get("claude_md_content", "")

            logger.info(
                "Phase 3 [%d/%d]: agent '%s' complete",
                i + 1, agent_count, agent["name"],
            )

        # ── Phase 4: Skills ─────────────────────────────────────────────
        skills_step = 2 + agent_count + 1

        # Collect all referenced skill names
        all_skill_names = set()
        for a in agents:
            for s in a.get("skill_names", []):
                all_skill_names.add(s)

        skills = []
        if all_skill_names:
            await _publish_progress(
                router, request_id,
                message="Generating skills...",
                step_number=skills_step, total_steps=total_steps,
            )

            skills_context = (
                f"Generate skills for this office.\n\n"
                f"Required skill names (referenced by agents): "
                f"{', '.join(sorted(all_skill_names))}\n\n"
                f"## Office Context\n"
                f"Office: {office_name}\n"
                f"Instructions: {instructions[:500]}\n\n"
                f"## Agents:\n{team_summary}\n\n"
                f"## Requirements\n{base_context}"
            )

            skills_result = await _run_chunk(
                container_name, SKILLS_PROMPT, skills_context,
            )
            skills = skills_result.get("skills", [])
            logger.info("Phase 4 complete: %d skills", len(skills))
        else:
            await _publish_progress(
                router, request_id,
                message="No skills needed",
                step_number=skills_step, total_steps=total_steps,
            )
            logger.info("Phase 4 skipped: no skills referenced")

        # ── Assemble final config ───────────────────────────────────────
        for agent in agents:
            agent.setdefault("model", "claude-sonnet-4-6")
            agent.setdefault("avatar_emoji", "\U0001f916")
            agent.setdefault("allowed_tools", ["Read", "Write"])
            agent.setdefault("system_prompt", "")
            agent.setdefault("claude_md_content", "")

        config = {
            "instructions": instructions,
            "agents": agents,
            "skills": skills,
        }

        await router.publish_event({
            "type": "setup_generation_complete",
            "request_id": request_id,
            "total_steps": total_steps,
            "config": config,
        })

        logger.info(
            "Office config generated: %d agents, %d skills",
            len(agents), len(skills),
        )

    except Exception as exc:
        logger.error("Config generation failed: %s", exc, exc_info=True)
        await router.publish_event({
            "type": "setup_generation_failed",
            "request_id": request_id,
            "error": str(exc),
        })


# ---------------------------------------------------------------------------
# Description analysis (unchanged — single call, always fast)
# ---------------------------------------------------------------------------

async def analyze_office_description(
    router: object,
    request_id: str,
    description: str,
    container_name: str,
) -> None:
    """Analyze a free-text office description into structured requirements."""
    try:
        raw_text = await _run_claude_cli(
            container_name, ANALYZE_SYSTEM_PROMPT, description,
        )
        requirements = _parse_json_response(raw_text)

        await router.publish_event({
            "type": "analyze_description_complete",
            "request_id": request_id,
            "requirements": requirements,
        })
        logger.info("Description analysis complete for request %s", request_id)

    except Exception as exc:
        logger.error("Description analysis failed: %s", exc, exc_info=True)
        await router.publish_event({
            "type": "analyze_description_failed",
            "request_id": request_id,
            "error": str(exc),
        })


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_user_prompt(
    office_name: str,
    office_description: str,
    requirements: dict[str, Any],
) -> str:
    parts = [f"Office: '{office_name}'"]
    if office_description:
        parts.append(f"Description: {office_description}")
    if requirements.get("responsibility_areas"):
        parts.append(f"\nResponsibility areas:\n{requirements['responsibility_areas']}")
    if requirements.get("desired_agents"):
        parts.append(f"\nDesired agents:\n{requirements['desired_agents']}")
    if requirements.get("workflows"):
        parts.append(f"\nWorkflows:\n{requirements['workflows']}")
    if requirements.get("additional_context"):
        parts.append(f"\nAdditional context:\n{requirements['additional_context']}")
    return "\n".join(parts)


def _parse_json_response(raw_text: str) -> dict[str, Any]:
    text = raw_text.strip()
    # Strip code fences (```json ... ```) — only the FIRST and LAST fence lines
    if text.startswith("```"):
        first_nl = text.index("\n")
        last_fence = text.rfind("```")
        if last_fence > first_nl:
            text = text[first_nl + 1:last_fence].strip()
        else:
            text = text[first_nl + 1:].strip()
    return json.loads(text)


async def _publish_progress(
    router: object,
    request_id: str,
    message: str,
    step_number: int,
    total_steps: int,
) -> None:
    await router.publish_event({
        "type": "setup_generation_progress",
        "request_id": request_id,
        "message": message,
        "step_number": step_number,
        "total_steps": total_steps,
    })
